In [1]:
## Homework 1
import pandas as pd
import numpy as np

df = pd.read_csv('YouTubeDataset_withChannelElapsed.csv')

In [2]:
df

,index,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,...,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,...,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0
1,1,1.133820,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.239130,59.326087,51,184,--NZRkXBV7k,...,0.000183,2076.647059,22080,44,3,0.016304,575.592391,0.494384,2015-03-30T04:04:40.000Z,2
2,2,0.668120,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023669,10.289941,72,338,--hoQ2sGG4M,...,0.000575,670.347222,71544,8,1,0.002959,142.795858,0.048613,2009-08-07T06:51:10.000Z,2
3,3,25.653505,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301,0.884178,172,22051,--sBoaqBlzA,...,0.000513,12306.523256,54096,161,6,0.000272,95.992109,0.360415,2011-08-04T01:07:38.000Z,10
4,4,52.773778,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545,10.004545,2777,220,--7h1S4neDM,...,0.000000,593.833273,30120,1,0,0.000000,7495.795455,0.073074,2014-04-29T15:44:44.000Z,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575605,575605,259.123802,UCoBsEPCif0cJr0XoH9vKVsA,10,25342567,0.011829,2.577992,3783,7270,2YwZKSyX5Pg,...,0.000534,6699.066085,49752,86,2,0.000275,3485.910179,0.376708,2012-02-01T04:01:17.000Z,10
575606,575606,0.322689,UC2AFyZm1gI81faexxhq5Mzg,2,30599,2.333333,4989.000000,15,3,2Y8Rtvd8cHc,...,-1.000000,2039.933333,93745,7,2,0.666667,10199.666667,0.159657,2007-01-25T14:38:49.000Z,-1
575607,575607,2.174518,UCXRQyRCOq8SwupXXqQ3mgAA,28,103855,0.227273,276.909091,61,22,2YhOrl3fzCM,...,0.000164,1702.540984,41496,5,9,0.409091,4720.681818,0.146809,2013-01-10T07:20:03.000Z,1
575608,575608,5.044453,UCtWqVyrfT_CrVeNx0UM4RjQ,24,363927,0.069519,10.331551,258,187,2Y3a5eS_q2s,...,0.002070,1410.569767,38352,13,1,0.005348,1946.133690,0.050375,2013-05-20T18:33:03.000Z,4
575609,575609,2.980623,UCrgYGNrCj4C9imt2NCneznA,20,141210,0.245345,17.361192,16,2417,2Y4e4gwEhaU,...,0.003956,8825.625000,47112,593,48,0.019859,58.423666,0.890686,2012-05-21T05:57:05.000Z,166

In [3]:
df['videoId'].duplicated().sum()

np.int64(19983)

In [4]:
df_unique = (
    df.groupby('videoId', as_index=False)
      .agg({
          'videoViewCount': 'max',   
          'videoLikeCount': 'max',
          'VideoCommentCount': 'max',
          'videoDislikeCount': 'max',
      })
)

df_unique['videoId'].duplicated().sum()

np.int64(0)

In [5]:
df_unique

,videoId,videoViewCount,videoLikeCount,VideoCommentCount,videoDislikeCount
0,---2pGwkL7M,3761,66,11,0
1,---9beuLW7Y,1551,0,0,0
2,---EnHBffak,7831,36,5,6
3,---GGMU_tSg,1525,8,1,0
4,---JEcw_1JE,1549,1,0,0
...,...,...,...,...,...
555622,zazd80d0nEE,157174,456,66,21
555623,zazdfx0TuUY,4889,4,0,0
555624,zazilSREH6A,1499,10,16,0
555625,zazoTwDFtgg,4931,7,0,0
555626,zazrjhMWf6M,4496,17,8,4

In [6]:
# 1.Calculate the average number of likes per video.
avg_likes = df_unique['videoLikeCount'].mean()
avg_likes

np.float64(292.75626274461104)

In [7]:
# 2. Compute the engagement rate for each video, where engagement rate is defined as the sum of likes, dislikes, 
# and comments divided by the total number of views for that video. 
# Finally, find the average engagement rate across all videos in the dataset.
df_unique['engagement_rate'] = (df_unique['videoLikeCount'] + df_unique['videoDislikeCount'] + df_unique['VideoCommentCount']) / df_unique['videoViewCount']
avg_engagement_rate = df_unique['engagement_rate'].mean()
avg_engagement_rate

np.float64(-0.0546247593454116)

In [8]:
# 3. Each video contains 500 bytes of metadata and a 200 KB thumbnail. Calculate the combined storage size for a single video in megabytes (MB)
metadata_mb = 500 / (1024 * 1024)  
thumbnail_mb = 200 / 1024 
total_mb = metadata_mb + thumbnail_mb
total_mb

0.19578933715820312

In [12]:
# 4. Each time someone engages with a video, the video’s metadata (likes , dislikes, comments, and thumbnail) 
# is accessed and potentially transmitted. The total data transfer refers to the sum of all data accessed for all engagements. 
# Using the total number of engagements and combined storage size of a single video (You calculated in Question 3), 
# estimate the total data transfer required for all engagements with videos in the dataset. 

mb = 0.1958
engagements = df_unique['videoLikeCount'].sum() + df_unique['videoDislikeCount'].sum() + df_unique['VideoCommentCount'].sum()
total_data = engagements * mb
total_data

np.float64(38173650.4512)

In [13]:
# 5. Estimate the number of views per minute, assuming the dataset spans 5 years with views uniformly distributed over time.
total_views = df_unique['videoViewCount'].sum()
total_mins = 5 * 365 * 24 * 60 # this should be correct..... 5 years, 365 days per year, 24 hours per day, 60 minutes per hour..... yeah..... idk if we should consider leap years though
views_per_min = total_views / total_mins
views_per_min

np.float64(12473.220591324201)

In [14]:
# 6. Estimate the amount of data accessed per minute to display video details to viewers.
data_per_min = views_per_min * mb
data_per_min

np.float64(2442.2565917812785)